### PR TITLE
convert xmt to udl

### PR DESCRIPTION
**Pull request by gevorg95**

### CODE REVIEW

**Comment by tiagogribeiro** [comment]
Thank's @gevorg95

**Comment by gevorg95** [comment]
Hi @tiagogribeiro! I mirrored your repo on the [intersystems-community](https://github.com/intersystems-community/cache-intersystems-design-patterns)!

**Comment by evshvarov** [comment]
Tiago! That means that every commit to your master and releases will be
mirrored to intersystems-community
<https://github.com/intersystems-community/cache-intersystems-design-patterns>
automatically.

**Comment by evshvarov** [comment]
This is fantastic repository, BTW. Thanks for creating and sharing this!

**Comment by tiagogribeiro** [comment]
Ohhh is nice.

Thank's Gevorg.
Att.
Tiago Goulart Ribeiro 

    Em segunda-feira, 16 de julho de 2018 10:22:04 BRT, Gevorg Arutiunian <notifications@github.com> escreveu:  
 
 
Hi @tiagogribeiro! I mirrored your repo on the intersystems-community!

**Pull request merged**
